const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync(require('node:path').join(__dirname, '../web/thread-ui.js'), 'utf8');
const ui = vm.runInNewContext(source + '\nThreadUI;', {});
assert.equal(ui.reasoningParts({summary:'**Checking code**\n\nAvailable details'}).headline, 'Checking code');
assert.equal(ui.reasoningParts({summary:'**Checking code**\n\nAvailable details'}).detail, 'Available details');
assert.equal(ui.reasoningParts({summary:'Summary',detail:'Native detail'}).detail, 'Native detail');
assert.equal(ui.reasoningParts({summary:'Summary'}).detail, '');
assert.equal(ui.reasoningParts({summary:''}).headline, '');
assert.equal(ui.reasoningParts({summary:'*Single marker*'}).headline, 'Single marker');
assert.equal(ui.durationText(null), '耗时未知');
assert.equal(ui.durationText(65000), '1 分 5 秒');
assert.equal(ui.durationText(3600000), '1 时 0 分');
assert.equal(ui.isCompacting({compactionPending:true}), true);
assert.equal(ui.isCompacting({connected:true,status:'active',turns:[{status:'inProgress',messages:[{kind:'contextCompaction'}]}]}), true);
assert.equal(ui.isCompacting({connected:false,status:'notLoaded',turns:[{status:'inProgress',messages:[{kind:'contextCompaction'}]}]}), false);
assert.equal(ui.isCompacting({turns:[{status:'completed',messages:[{kind:'contextCompaction'}]}]}), false);
const final={role:'assistant',phase:'final_answer',text:'Result'};
assert.equal(ui.finalMessage({messages:[final,{role:'assistant',phase:'commentary',text:'Update'}]}), final);
assert.equal(ui.completedTurn({id:'old',status:'inProgress'},{turns:[{id:'old'},{id:'new'}]}), true);
assert.equal(ui.completedTurn({id:'new',status:'inProgress'},{turns:[{id:'new'}]}), false);
assert.equal(ui.completedTurn({id:'new',status:'completed'},{turns:[{id:'new'}]}), true);
assert.equal(ui.revealStep(0, 'abcdef', 32, 100), 3);
assert.equal(ui.revealStep(0, '😀test', 10, 100), 0);
assert.equal(ui.revealStep(0, '😀test', 20, 100), 2);
assert.equal(ui.revealStep(4, 'abcdef', 100, 100), 6);
assert.equal(ui.settledPrefix('First\n\nsecond'), 7);
assert.equal(ui.settledPrefix('```js\n\npending'), 0);
assert.equal(ui.settledPrefix('````js\n```\n\npending'), 0);
assert.equal(ui.settledPrefix('```js\nx\n```\n\npending'), 13);
console.log('25 thread UI assertions passed');
