const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync(require('node:path').join(__dirname, '../web/thread-ui.js'), 'utf8');
const ui = vm.runInNewContext(source + '\nThreadUI;', {});
assert.equal(ui.reasoningParts({summary:'**Checking code**\n\nAvailable details'}).headline, 'Checking code');
assert.equal(ui.reasoningParts({summary:'**Checking code**\n\nAvailable details'}).detail, 'Available details');
assert.equal(ui.reasoningParts({summary:'Summary',detail:'Native detail'}).detail, 'Native detail');
assert.equal(ui.reasoningParts({summary:'Summary'}).detail, '');
assert.equal(ui.reasoningParts({summary:''}).headline, '');
assert.equal(ui.reasoningParts({summary:'*Single marker*'}).headline, 'Single marker');
assert.equal(ui.durationText(null), '耗时未知');
assert.equal(ui.durationText(65000), '1 分 5 秒');
assert.equal(ui.durationText(3600000), '1 时 0 分');
assert.equal(ui.isCompacting({compactionPending:true}), true);
assert.equal(ui.isCompacting({connected:true,status:'active',turns:[{status:'inProgress',messages:[{kind:'contextCompaction',status:'inProgress'}]}]}), true);
assert.equal(ui.isCompacting({connected:true,status:'active',turns:[{status:'inProgress',messages:[{kind:'contextCompaction'}]}]}), false);
assert.equal(ui.isCompacting({connected:true,status:'active',turns:[{status:'inProgress',messages:[{kind:'contextCompaction',status:'failed'}]}]}), false);
const compact={kind:'contextCompaction',role:'activity',status:'completed'};
const compactView={turns:[{id:'a',messages:[{role:'assistant',text:'Done'},compact,compact]},{id:'b',messages:[compact]}]};
assert.equal(ui.compactionRecords(compactView).size,1);
assert.equal(ui.compactionRecords(compactView).get('b').get(0),3);
assert.equal(ui.compactionRecords({...compactView,compactionPending:true}).size,0);
assert.equal(ui.compactionRecords({connected:true,status:'active',turns:[{id:'live',status:'inProgress',messages:[
  {...compact,status:'inProgress'},{role:'activity',kind:'commandExecution'}]}]}).size,0);
assert.equal(ui.compactionRecords({turns:[{id:'empty',status:'completed',messages:[compact,{role:'assistant',text:''},compact]}]}).get('empty').get(2),2);
assert.equal(ui.compactionRecords({turns:[{id:'a',messages:[compact,{role:'user',text:'Next'},compact]}]}).get('a').size,2);
assert.equal(ui.isCompacting({connected:false,status:'notLoaded',turns:[{status:'inProgress',messages:[{kind:'contextCompaction'}]}]}), false);
assert.equal(ui.isCompacting({turns:[{status:'completed',messages:[{kind:'contextCompaction'}]}]}), false);
const final={role:'assistant',phase:'final_answer',text:'Result'};
assert.equal(ui.finalMessage({messages:[final,{role:'assistant',phase:'commentary',text:'Update'}]}), final);
assert.equal(ui.completedTurn({id:'old',status:'inProgress'},{turns:[{id:'old'},{id:'new'}]}), true);
assert.equal(ui.completedTurn({id:'new',status:'inProgress'},{turns:[{id:'new'}]}), false);
assert.equal(ui.completedTurn({id:'new',status:'completed'},{turns:[{id:'new'}]}), true);
assert.equal(ui.revealStep(0, 'abcdef', 32, 100), 3);
assert.equal(ui.revealStep(0, '😀test', 10, 100), 0);
assert.equal(ui.revealStep(0, '😀test', 20, 100), 2);
assert.equal(ui.revealStep(4, 'abcdef', 100, 100), 6);
assert.equal(ui.settledPrefix('First\n\nsecond'), 7);
assert.equal(ui.settledPrefix('```js\n\npending'), 0);
assert.equal(ui.settledPrefix('````js\n```\n\npending'), 0);
assert.equal(ui.settledPrefix('```js\nx\n```\n\npending'), 13);
assert.equal(ui.inputMaxHeight(350, 180), 70);
assert.equal(ui.inputMaxHeight(300, 210), 40);
assert.equal(ui.inputMaxHeight(900, 180), 150);
assert.equal(ui.diffLineKind('+++ b/app.js'), 'meta');
assert.equal(ui.diffLineKind('--- a/app.js'), 'meta');
assert.equal(ui.diffLineKind('+ added'), 'add');
assert.equal(ui.diffLineKind('- removed'), 'remove');
assert.equal(ui.diffLineKind('@@ -1 +1 @@'), 'hunk');
assert.equal(ui.diffLineKind(' unchanged'), 'context');
assert.equal(ui.diffLineKind('*** Update File: app.js'), 'meta');
assert.equal(ui.activityPresentation({kind:'commandExecution',text:'npm test',output:'OK'}).call, 'npm test');
assert.equal(ui.activityPresentation({kind:'dynamicToolCall',title:'exec_command',
  text:'{"cmd":"npm test","workdir":"C:/demo","yield_time_ms":1000}'}).call, '目录：C:/demo\nnpm test');
assert.equal(ui.activityPresentation({kind:'function_call',text:JSON.stringify({
  name:'exec_command',arguments:'{"cmd":"node test.cjs"}'})}).call, 'node test.cjs');
assert.equal(ui.activityPresentation({kind:'custom_tool_call',text:JSON.stringify({
  name:'apply_patch',input:'*** Begin Patch\n*** Update File: app.js\n@@\n-old\n+new\n*** End Patch'})}).diff.includes('+new'), true);
assert.equal(ui.activityPresentation({kind:'dynamicToolCall',title:'search',text:'{"query":"hello","path":"src"}'}).call, '搜索：hello\n范围：src');
assert.equal(ui.activityPresentation({kind:'fileChange',text:'app.js\n@@ -1 +1 @@\n-old\n+new'}).diff.includes('-old'), true);
assert.equal(ui.activityPresentation({kind:'mcpToolCall',title:'tool',text:'{"password":"private","schema":{"data":"hidden"},"path":"readme"}'}).call, '文件：readme');
assert.equal(ui.activityPresentation({kind:'mcpToolCall',text:'{}',output:'[{"type":"text","text":"Readable output"}]'}).output, 'Readable output');
assert.equal(ui.activityPresentation({kind:'mcpToolCall',text:'{incomplete'}).call, '正在接收调用信息…');
assert.equal(ui.activityPresentation({kind:'dynamicToolCall',text:JSON.stringify({tool_uses:[
  {recipient_name:'functions.exec_command',parameters:{cmd:'one'}},
  {recipient_name:'functions.exec_command',parameters:{cmd:'two'}}]})}).call, 'one\n\ntwo');
assert.equal(ui.activityPresentation({kind:'function_call_output',text:'{"output":"Done","call_id":"ignored"}'}).call, '调用结果');
assert.equal(ui.activityPresentation({kind:'function_call_output',text:'{"output":"Done","call_id":"ignored"}'}).output, 'Done');
assert.equal(ui.activityPresentation({kind:'custom_tool_call',text:'{"name":"tool","arguments":{}}'}).diff, '');
assert.equal(ui.activityIcon({kind:'mcpToolCall'}, 'server · tool'), 'PlugZap');
assert.equal(ui.activityIcon({kind:'function_call'}, 'mcp__server__tool'), 'PlugZap');
assert.equal(ui.activityIcon({kind:'function_call'}, 'functions.read_mcp_resource'), 'PlugZap');
assert.equal(ui.activityIcon({kind:'skill'}, 'anything'), 'Sparkles');
assert.equal(ui.activityIcon({kind:'commandExecution'}, 'exec_command'), 'Terminal');
assert.equal(ui.filePresentation({path:'new.js',kind:{type:'add'},diff:'one\n\ntwo\n'}).diff, '+one\n+\n+two');
assert.equal(ui.filePresentation({path:'empty',kind:'add',diff:''}).diff, '');
assert.equal(ui.filePresentation({path:'updated',kind:{type:'update'},diff:'one\ntwo'}).created, false);
assert.equal(ui.filePresentation({path:'unknown',diff:'+added'}).label, '修改文件');
assert.equal(ui.filePresentation({path:'new',kind:'add',diff:'@@ -0,0 +1 @@\n+one'}).diff, '@@ -0,0 +1 @@\n+one');
assert.equal(ui.activityPresentation({kind:'fileChange',text:'new.js',changes:[{path:'new.js',kind:{type:'add'},diff:'one'}]}).title, '创建文件');
assert.equal(ui.activityPresentation({kind:'custom_tool_call',text:JSON.stringify({name:'apply_patch',
  input:'*** Begin Patch\n*** Add File: new.js\n+one\n*** End Patch'})}).title, '创建文件');
assert.equal(ui.activityIcon({kind:'function_call'}, 'functions.exec_command'), 'Terminal');
assert.equal(ui.activityPresentation({kind:'dynamicToolCall',title:'exec_command',text:'{"cmd":"node tests.js","cwd":"C:/Demo"}'}).command, 'node tests.js');
assert.equal(ui.activityPresentation({kind:'dynamicToolCall',title:'exec_command',text:'{"cmd":"node tests.js"}'}).title, '执行命令');
assert.equal(ui.toolResult({content:[{type:'text',text:'{"output":"All tests pass","exit_code":0,"wall_time_seconds":1.25}'}]}).text, 'All tests pass');
assert.equal(ui.toolResult({content:[{type:'text',text:'{"output":"All tests pass","exit_code":0}'}]}).exitCode,0);
assert.equal(ui.toolResult({wall_time_seconds:1.25,output:'OK'}).durationMs,1250);
assert.equal(ui.toolResult({isError:true,content:[{type:'text',text:'Denied'}]}).failed,true);
assert.equal(ui.toolResult([{type:'image',data:'PRIVATE_BINARY'},{type:'text',text:'Result'}]).text,'[图片结果]\n\nResult');
assert.equal(ui.toolResult({type:'resource_link',name:'Report',uri:'demo://report'}).text,'Report · demo://report');
assert.equal(ui.toolResult({output:'<script>bad()</script>'}).text,'<script>bad()</script>');
assert.equal(ui.toolResult({type:'resource',resource:{uri:'demo://binary',blob:'PRIVATE_BINARY'}}).text,'demo://binary');
console.log('Thread UI assertions passed');
